package goober.hi

import goober.free.chime.ChimeIO
import software.amazon.awssdk.services.chime.model._


object chime {
  import goober.free.{chime ⇒ free}

  object model {
    import goober.hi.util.BuilderSyntax._

    // Methods for constructing model classes, requests, etc.
    // AssociatePhoneNumberWithUserRequest
    // AssociatePhoneNumbersWithVoiceConnectorRequest
    // AssociatePhoneNumbersWithVoiceConnectorGroupRequest
    // AssociateSigninDelegateGroupsWithAccountRequest
    // BatchCreateAttendeeRequest
    // BatchCreateChannelMembershipRequest
    // BatchCreateRoomMembershipRequest
    // BatchDeletePhoneNumberRequest
    // BatchSuspendUserRequest
    // BatchUnsuspendUserRequest
    // BatchUpdatePhoneNumberRequest
    // BatchUpdateUserRequest
    // CreateAccountRequest
    // CreateAppInstanceRequest
    // CreateAppInstanceAdminRequest
    // CreateAppInstanceUserRequest
    // CreateAttendeeRequest
    // CreateBotRequest
    // CreateChannelRequest
    // CreateChannelBanRequest
    // CreateChannelMembershipRequest
    // CreateChannelModeratorRequest
    // CreateMeetingRequest
    // CreateMeetingDialOutRequest
    // CreateMeetingWithAttendeesRequest
    // CreatePhoneNumberOrderRequest
    // CreateProxySessionRequest
    // CreateRoomRequest
    // CreateRoomMembershipRequest
    // CreateSipMediaApplicationRequest
    // CreateSipMediaApplicationCallRequest
    // CreateSipRuleRequest
    // CreateUserRequest
    // CreateVoiceConnectorRequest
    // CreateVoiceConnectorGroupRequest
    // DeleteAccountRequest
    // DeleteAppInstanceRequest
    // DeleteAppInstanceAdminRequest
    // DeleteAppInstanceStreamingConfigurationsRequest
    // DeleteAppInstanceUserRequest
    // DeleteAttendeeRequest
    // DeleteChannelRequest
    // DeleteChannelBanRequest
    // DeleteChannelMembershipRequest
    // DeleteChannelMessageRequest
    // DeleteChannelModeratorRequest
    // DeleteEventsConfigurationRequest
    // DeleteMeetingRequest
    // DeletePhoneNumberRequest
    // DeleteProxySessionRequest
    // DeleteRoomRequest
    // DeleteRoomMembershipRequest
    // DeleteSipMediaApplicationRequest
    // DeleteSipRuleRequest
    // DeleteVoiceConnectorRequest
    // DeleteVoiceConnectorEmergencyCallingConfigurationRequest
    // DeleteVoiceConnectorGroupRequest
    // DeleteVoiceConnectorOriginationRequest
    // DeleteVoiceConnectorProxyRequest
    // DeleteVoiceConnectorStreamingConfigurationRequest
    // DeleteVoiceConnectorTerminationRequest
    // DeleteVoiceConnectorTerminationCredentialsRequest
    // DescribeAppInstanceRequest
    // DescribeAppInstanceAdminRequest
    // DescribeAppInstanceUserRequest
    // DescribeChannelRequest
    // DescribeChannelBanRequest
    // DescribeChannelMembershipRequest
    // DescribeChannelMembershipForAppInstanceUserRequest
    // DescribeChannelModeratedByAppInstanceUserRequest
    // DescribeChannelModeratorRequest
    // DisassociatePhoneNumberFromUserRequest
    // DisassociatePhoneNumbersFromVoiceConnectorRequest
    // DisassociatePhoneNumbersFromVoiceConnectorGroupRequest
    // DisassociateSigninDelegateGroupsFromAccountRequest
    // GetAccountRequest
    // GetAccountSettingsRequest
    // GetAppInstanceRetentionSettingsRequest
    // GetAppInstanceStreamingConfigurationsRequest
    // GetAttendeeRequest
    // GetBotRequest
    // GetChannelMessageRequest
    // GetEventsConfigurationRequest
    // GetGlobalSettingsRequest
    // GetMeetingRequest
    // GetMessagingSessionEndpointRequest
    // GetPhoneNumberRequest
    // GetPhoneNumberOrderRequest
    // GetPhoneNumberSettingsRequest
    // GetProxySessionRequest
    // GetRetentionSettingsRequest
    // GetRoomRequest
    // GetSipMediaApplicationRequest
    // GetSipMediaApplicationLoggingConfigurationRequest
    // GetSipRuleRequest
    // GetUserRequest
    // GetUserSettingsRequest
    // GetVoiceConnectorRequest
    // GetVoiceConnectorEmergencyCallingConfigurationRequest
    // GetVoiceConnectorGroupRequest
    // GetVoiceConnectorLoggingConfigurationRequest
    // GetVoiceConnectorOriginationRequest
    // GetVoiceConnectorProxyRequest
    // GetVoiceConnectorStreamingConfigurationRequest
    // GetVoiceConnectorTerminationRequest
    // GetVoiceConnectorTerminationHealthRequest
    // InviteUsersRequest
    // ListAccountsRequest
    // ListAppInstanceAdminsRequest
    // ListAppInstanceUsersRequest
    // ListAppInstancesRequest
    // ListAttendeeTagsRequest
    // ListAttendeesRequest
    // ListBotsRequest
    // ListChannelBansRequest
    // ListChannelMembershipsRequest
    // ListChannelMembershipsForAppInstanceUserRequest
    // ListChannelMessagesRequest
    // ListChannelModeratorsRequest
    // ListChannelsRequest
    // ListChannelsModeratedByAppInstanceUserRequest
    // ListMeetingTagsRequest
    // ListMeetingsRequest
    // ListPhoneNumberOrdersRequest
    // ListPhoneNumbersRequest
    // ListProxySessionsRequest
    // ListRoomMembershipsRequest
    // ListRoomsRequest
    // ListSipMediaApplicationsRequest
    // ListSipRulesRequest
    // ListSupportedPhoneNumberCountriesRequest
    // ListTagsForResourceRequest
    // ListUsersRequest
    // ListVoiceConnectorGroupsRequest
    // ListVoiceConnectorTerminationCredentialsRequest
    // ListVoiceConnectorsRequest
    // LogoutUserRequest
    // PutAppInstanceRetentionSettingsRequest
    // PutAppInstanceStreamingConfigurationsRequest
    // PutEventsConfigurationRequest
    // PutRetentionSettingsRequest
    // PutSipMediaApplicationLoggingConfigurationRequest
    // PutVoiceConnectorEmergencyCallingConfigurationRequest
    // PutVoiceConnectorLoggingConfigurationRequest
    // PutVoiceConnectorOriginationRequest
    // PutVoiceConnectorProxyRequest
    // PutVoiceConnectorStreamingConfigurationRequest
    // PutVoiceConnectorTerminationRequest
    // PutVoiceConnectorTerminationCredentialsRequest
    // RedactChannelMessageRequest
    // RedactConversationMessageRequest
    // RedactRoomMessageRequest
    // RegenerateSecurityTokenRequest
    // ResetPersonalPinRequest
    // RestorePhoneNumberRequest
    // SearchAvailablePhoneNumbersRequest
    // SendChannelMessageRequest
    // TagAttendeeRequest
    // TagMeetingRequest
    // TagResourceRequest
    // UntagAttendeeRequest
    // UntagMeetingRequest
    // UntagResourceRequest
    // UpdateAccountRequest
    // UpdateAccountSettingsRequest
    // UpdateAppInstanceRequest
    // UpdateAppInstanceUserRequest
    // UpdateBotRequest
    // UpdateChannelRequest
    // UpdateChannelMessageRequest
    // UpdateChannelReadMarkerRequest
    // UpdateGlobalSettingsRequest
    // UpdatePhoneNumberRequest
    // UpdatePhoneNumberSettingsRequest
    // UpdateProxySessionRequest
    // UpdateRoomRequest
    // UpdateRoomMembershipRequest
    // UpdateSipMediaApplicationRequest
    // UpdateSipRuleRequest
    // UpdateUserRequest
    // UpdateUserSettingsRequest
    // UpdateVoiceConnectorRequest
    // UpdateVoiceConnectorGroupRequest

  }

  // smartConstructors that take paramteers derived from mandatory & optional fields of requests
}
