package goober.hi

import goober.free.ec2.Ec2IO
import software.amazon.awssdk.services.ec2.model._


object ec2 {
  import goober.free.{ec2 ⇒ free}

  object model {
    import goober.hi.util.BuilderSyntax._

    // Methods for constructing model classes, requests, etc.
    // AcceptReservedInstancesExchangeQuoteRequest
    // AcceptTransitGatewayMulticastDomainAssociationsRequest
    // AcceptTransitGatewayPeeringAttachmentRequest
    // AcceptTransitGatewayVpcAttachmentRequest
    // AcceptVpcEndpointConnectionsRequest
    // AcceptVpcPeeringConnectionRequest
    // AdvertiseByoipCidrRequest
    // AllocateAddressRequest
    // AllocateHostsRequest
    // ApplySecurityGroupsToClientVpnTargetNetworkRequest
    // AssignIpv6AddressesRequest
    // AssignPrivateIpAddressesRequest
    // AssociateAddressRequest
    // AssociateClientVpnTargetNetworkRequest
    // AssociateDhcpOptionsRequest
    // AssociateEnclaveCertificateIamRoleRequest
    // AssociateIamInstanceProfileRequest
    // AssociateRouteTableRequest
    // AssociateSubnetCidrBlockRequest
    // AssociateTransitGatewayMulticastDomainRequest
    // AssociateTransitGatewayRouteTableRequest
    // AssociateVpcCidrBlockRequest
    // AttachClassicLinkVpcRequest
    // AttachInternetGatewayRequest
    // AttachNetworkInterfaceRequest
    // AttachVolumeRequest
    // AttachVpnGatewayRequest
    // AuthorizeClientVpnIngressRequest
    // AuthorizeSecurityGroupEgressRequest
    // AuthorizeSecurityGroupIngressRequest
    // BundleInstanceRequest
    // CancelBundleTaskRequest
    // CancelCapacityReservationRequest
    // CancelConversionTaskRequest
    // CancelExportTaskRequest
    // CancelImportTaskRequest
    // CancelReservedInstancesListingRequest
    // CancelSpotFleetRequestsRequest
    // CancelSpotInstanceRequestsRequest
    // ConfirmProductInstanceRequest
    // CopyFpgaImageRequest
    // CopyImageRequest
    // CopySnapshotRequest
    // CreateCapacityReservationRequest
    // CreateCarrierGatewayRequest
    // CreateClientVpnEndpointRequest
    // CreateClientVpnRouteRequest
    // CreateCustomerGatewayRequest
    // CreateDefaultSubnetRequest
    // CreateDefaultVpcRequest
    // CreateDhcpOptionsRequest
    // CreateEgressOnlyInternetGatewayRequest
    // CreateFleetRequest
    // CreateFlowLogsRequest
    // CreateFpgaImageRequest
    // CreateImageRequest
    // CreateInstanceExportTaskRequest
    // CreateInternetGatewayRequest
    // CreateKeyPairRequest
    // CreateLaunchTemplateRequest
    // CreateLaunchTemplateVersionRequest
    // CreateLocalGatewayRouteRequest
    // CreateLocalGatewayRouteTableVpcAssociationRequest
    // CreateManagedPrefixListRequest
    // CreateNatGatewayRequest
    // CreateNetworkAclEntryRequest
    // CreateNetworkAclRequest
    // CreateNetworkInsightsPathRequest
    // CreateNetworkInterfacePermissionRequest
    // CreateNetworkInterfaceRequest
    // CreatePlacementGroupRequest
    // CreateReplaceRootVolumeTaskRequest
    // CreateReservedInstancesListingRequest
    // CreateRestoreImageTaskRequest
    // CreateRouteRequest
    // CreateRouteTableRequest
    // CreateSecurityGroupRequest
    // CreateSnapshotRequest
    // CreateSnapshotsRequest
    // CreateSpotDatafeedSubscriptionRequest
    // CreateStoreImageTaskRequest
    // CreateSubnetRequest
    // CreateTagsRequest
    // CreateTrafficMirrorFilterRequest
    // CreateTrafficMirrorFilterRuleRequest
    // CreateTrafficMirrorSessionRequest
    // CreateTrafficMirrorTargetRequest
    // CreateTransitGatewayConnectPeerRequest
    // CreateTransitGatewayConnectRequest
    // CreateTransitGatewayMulticastDomainRequest
    // CreateTransitGatewayPeeringAttachmentRequest
    // CreateTransitGatewayPrefixListReferenceRequest
    // CreateTransitGatewayRequest
    // CreateTransitGatewayRouteRequest
    // CreateTransitGatewayRouteTableRequest
    // CreateTransitGatewayVpcAttachmentRequest
    // CreateVolumeRequest
    // CreateVpcEndpointConnectionNotificationRequest
    // CreateVpcEndpointRequest
    // CreateVpcEndpointServiceConfigurationRequest
    // CreateVpcPeeringConnectionRequest
    // CreateVpcRequest
    // CreateVpnConnectionRequest
    // CreateVpnConnectionRouteRequest
    // CreateVpnGatewayRequest
    // DeleteCarrierGatewayRequest
    // DeleteClientVpnEndpointRequest
    // DeleteClientVpnRouteRequest
    // DeleteCustomerGatewayRequest
    // DeleteDhcpOptionsRequest
    // DeleteEgressOnlyInternetGatewayRequest
    // DeleteFleetsRequest
    // DeleteFlowLogsRequest
    // DeleteFpgaImageRequest
    // DeleteInternetGatewayRequest
    // DeleteKeyPairRequest
    // DeleteLaunchTemplateRequest
    // DeleteLaunchTemplateVersionsRequest
    // DeleteLocalGatewayRouteRequest
    // DeleteLocalGatewayRouteTableVpcAssociationRequest
    // DeleteManagedPrefixListRequest
    // DeleteNatGatewayRequest
    // DeleteNetworkAclEntryRequest
    // DeleteNetworkAclRequest
    // DeleteNetworkInsightsAnalysisRequest
    // DeleteNetworkInsightsPathRequest
    // DeleteNetworkInterfacePermissionRequest
    // DeleteNetworkInterfaceRequest
    // DeletePlacementGroupRequest
    // DeleteQueuedReservedInstancesRequest
    // DeleteRouteRequest
    // DeleteRouteTableRequest
    // DeleteSecurityGroupRequest
    // DeleteSnapshotRequest
    // DeleteSpotDatafeedSubscriptionRequest
    // DeleteSubnetRequest
    // DeleteTagsRequest
    // DeleteTrafficMirrorFilterRequest
    // DeleteTrafficMirrorFilterRuleRequest
    // DeleteTrafficMirrorSessionRequest
    // DeleteTrafficMirrorTargetRequest
    // DeleteTransitGatewayConnectPeerRequest
    // DeleteTransitGatewayConnectRequest
    // DeleteTransitGatewayMulticastDomainRequest
    // DeleteTransitGatewayPeeringAttachmentRequest
    // DeleteTransitGatewayPrefixListReferenceRequest
    // DeleteTransitGatewayRequest
    // DeleteTransitGatewayRouteRequest
    // DeleteTransitGatewayRouteTableRequest
    // DeleteTransitGatewayVpcAttachmentRequest
    // DeleteVolumeRequest
    // DeleteVpcEndpointConnectionNotificationsRequest
    // DeleteVpcEndpointServiceConfigurationsRequest
    // DeleteVpcEndpointsRequest
    // DeleteVpcPeeringConnectionRequest
    // DeleteVpcRequest
    // DeleteVpnConnectionRequest
    // DeleteVpnConnectionRouteRequest
    // DeleteVpnGatewayRequest
    // DeprovisionByoipCidrRequest
    // DeregisterImageRequest
    // DeregisterInstanceEventNotificationAttributesRequest
    // DeregisterTransitGatewayMulticastGroupMembersRequest
    // DeregisterTransitGatewayMulticastGroupSourcesRequest
    // DescribeAccountAttributesRequest
    // DescribeAddressesAttributeRequest
    // DescribeAddressesRequest
    // DescribeAggregateIdFormatRequest
    // DescribeAvailabilityZonesRequest
    // DescribeBundleTasksRequest
    // DescribeByoipCidrsRequest
    // DescribeCapacityReservationsRequest
    // DescribeCarrierGatewaysRequest
    // DescribeClassicLinkInstancesRequest
    // DescribeClientVpnAuthorizationRulesRequest
    // DescribeClientVpnConnectionsRequest
    // DescribeClientVpnEndpointsRequest
    // DescribeClientVpnRoutesRequest
    // DescribeClientVpnTargetNetworksRequest
    // DescribeCoipPoolsRequest
    // DescribeConversionTasksRequest
    // DescribeCustomerGatewaysRequest
    // DescribeDhcpOptionsRequest
    // DescribeEgressOnlyInternetGatewaysRequest
    // DescribeElasticGpusRequest
    // DescribeExportImageTasksRequest
    // DescribeExportTasksRequest
    // DescribeFastSnapshotRestoresRequest
    // DescribeFleetHistoryRequest
    // DescribeFleetInstancesRequest
    // DescribeFleetsRequest
    // DescribeFlowLogsRequest
    // DescribeFpgaImageAttributeRequest
    // DescribeFpgaImagesRequest
    // DescribeHostReservationOfferingsRequest
    // DescribeHostReservationsRequest
    // DescribeHostsRequest
    // DescribeIamInstanceProfileAssociationsRequest
    // DescribeIdFormatRequest
    // DescribeIdentityIdFormatRequest
    // DescribeImageAttributeRequest
    // DescribeImagesRequest
    // DescribeImportImageTasksRequest
    // DescribeImportSnapshotTasksRequest
    // DescribeInstanceAttributeRequest
    // DescribeInstanceCreditSpecificationsRequest
    // DescribeInstanceEventNotificationAttributesRequest
    // DescribeInstanceStatusRequest
    // DescribeInstanceTypeOfferingsRequest
    // DescribeInstanceTypesRequest
    // DescribeInstancesRequest
    // DescribeInternetGatewaysRequest
    // DescribeIpv6PoolsRequest
    // DescribeKeyPairsRequest
    // DescribeLaunchTemplateVersionsRequest
    // DescribeLaunchTemplatesRequest
    // DescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociationsRequest
    // DescribeLocalGatewayRouteTableVpcAssociationsRequest
    // DescribeLocalGatewayRouteTablesRequest
    // DescribeLocalGatewayVirtualInterfaceGroupsRequest
    // DescribeLocalGatewayVirtualInterfacesRequest
    // DescribeLocalGatewaysRequest
    // DescribeManagedPrefixListsRequest
    // DescribeMovingAddressesRequest
    // DescribeNatGatewaysRequest
    // DescribeNetworkAclsRequest
    // DescribeNetworkInsightsAnalysesRequest
    // DescribeNetworkInsightsPathsRequest
    // DescribeNetworkInterfaceAttributeRequest
    // DescribeNetworkInterfacePermissionsRequest
    // DescribeNetworkInterfacesRequest
    // DescribePlacementGroupsRequest
    // DescribePrefixListsRequest
    // DescribePrincipalIdFormatRequest
    // DescribePublicIpv4PoolsRequest
    // DescribeRegionsRequest
    // DescribeReplaceRootVolumeTasksRequest
    // DescribeReservedInstancesListingsRequest
    // DescribeReservedInstancesModificationsRequest
    // DescribeReservedInstancesOfferingsRequest
    // DescribeReservedInstancesRequest
    // DescribeRouteTablesRequest
    // DescribeScheduledInstanceAvailabilityRequest
    // DescribeScheduledInstancesRequest
    // DescribeSecurityGroupReferencesRequest
    // DescribeSecurityGroupsRequest
    // DescribeSnapshotAttributeRequest
    // DescribeSnapshotsRequest
    // DescribeSpotDatafeedSubscriptionRequest
    // DescribeSpotFleetInstancesRequest
    // DescribeSpotFleetRequestHistoryRequest
    // DescribeSpotFleetRequestsRequest
    // DescribeSpotInstanceRequestsRequest
    // DescribeSpotPriceHistoryRequest
    // DescribeStaleSecurityGroupsRequest
    // DescribeStoreImageTasksRequest
    // DescribeSubnetsRequest
    // DescribeTagsRequest
    // DescribeTrafficMirrorFiltersRequest
    // DescribeTrafficMirrorSessionsRequest
    // DescribeTrafficMirrorTargetsRequest
    // DescribeTransitGatewayAttachmentsRequest
    // DescribeTransitGatewayConnectPeersRequest
    // DescribeTransitGatewayConnectsRequest
    // DescribeTransitGatewayMulticastDomainsRequest
    // DescribeTransitGatewayPeeringAttachmentsRequest
    // DescribeTransitGatewayRouteTablesRequest
    // DescribeTransitGatewayVpcAttachmentsRequest
    // DescribeTransitGatewaysRequest
    // DescribeVolumeAttributeRequest
    // DescribeVolumeStatusRequest
    // DescribeVolumesModificationsRequest
    // DescribeVolumesRequest
    // DescribeVpcAttributeRequest
    // DescribeVpcClassicLinkDnsSupportRequest
    // DescribeVpcClassicLinkRequest
    // DescribeVpcEndpointConnectionNotificationsRequest
    // DescribeVpcEndpointConnectionsRequest
    // DescribeVpcEndpointServiceConfigurationsRequest
    // DescribeVpcEndpointServicePermissionsRequest
    // DescribeVpcEndpointServicesRequest
    // DescribeVpcEndpointsRequest
    // DescribeVpcPeeringConnectionsRequest
    // DescribeVpcsRequest
    // DescribeVpnConnectionsRequest
    // DescribeVpnGatewaysRequest
    // DetachClassicLinkVpcRequest
    // DetachInternetGatewayRequest
    // DetachNetworkInterfaceRequest
    // DetachVolumeRequest
    // DetachVpnGatewayRequest
    // DisableEbsEncryptionByDefaultRequest
    // DisableFastSnapshotRestoresRequest
    // DisableImageDeprecationRequest
    // DisableSerialConsoleAccessRequest
    // DisableTransitGatewayRouteTablePropagationRequest
    // DisableVgwRoutePropagationRequest
    // DisableVpcClassicLinkDnsSupportRequest
    // DisableVpcClassicLinkRequest
    // DisassociateAddressRequest
    // DisassociateClientVpnTargetNetworkRequest
    // DisassociateEnclaveCertificateIamRoleRequest
    // DisassociateIamInstanceProfileRequest
    // DisassociateRouteTableRequest
    // DisassociateSubnetCidrBlockRequest
    // DisassociateTransitGatewayMulticastDomainRequest
    // DisassociateTransitGatewayRouteTableRequest
    // DisassociateVpcCidrBlockRequest
    // EnableEbsEncryptionByDefaultRequest
    // EnableFastSnapshotRestoresRequest
    // EnableImageDeprecationRequest
    // EnableSerialConsoleAccessRequest
    // EnableTransitGatewayRouteTablePropagationRequest
    // EnableVgwRoutePropagationRequest
    // EnableVolumeIoRequest
    // EnableVpcClassicLinkDnsSupportRequest
    // EnableVpcClassicLinkRequest
    // ExportClientVpnClientCertificateRevocationListRequest
    // ExportClientVpnClientConfigurationRequest
    // ExportImageRequest
    // ExportTransitGatewayRoutesRequest
    // GetAssociatedEnclaveCertificateIamRolesRequest
    // GetAssociatedIpv6PoolCidrsRequest
    // GetCapacityReservationUsageRequest
    // GetCoipPoolUsageRequest
    // GetConsoleOutputRequest
    // GetConsoleScreenshotRequest
    // GetDefaultCreditSpecificationRequest
    // GetEbsDefaultKmsKeyIdRequest
    // GetEbsEncryptionByDefaultRequest
    // GetFlowLogsIntegrationTemplateRequest
    // GetGroupsForCapacityReservationRequest
    // GetHostReservationPurchasePreviewRequest
    // GetLaunchTemplateDataRequest
    // GetManagedPrefixListAssociationsRequest
    // GetManagedPrefixListEntriesRequest
    // GetPasswordDataRequest
    // GetReservedInstancesExchangeQuoteRequest
    // GetSerialConsoleAccessStatusRequest
    // GetTransitGatewayAttachmentPropagationsRequest
    // GetTransitGatewayMulticastDomainAssociationsRequest
    // GetTransitGatewayPrefixListReferencesRequest
    // GetTransitGatewayRouteTableAssociationsRequest
    // GetTransitGatewayRouteTablePropagationsRequest
    // ImportClientVpnClientCertificateRevocationListRequest
    // ImportImageRequest
    // ImportInstanceRequest
    // ImportKeyPairRequest
    // ImportSnapshotRequest
    // ImportVolumeRequest
    // ModifyAddressAttributeRequest
    // ModifyAvailabilityZoneGroupRequest
    // ModifyCapacityReservationRequest
    // ModifyClientVpnEndpointRequest
    // ModifyDefaultCreditSpecificationRequest
    // ModifyEbsDefaultKmsKeyIdRequest
    // ModifyFleetRequest
    // ModifyFpgaImageAttributeRequest
    // ModifyHostsRequest
    // ModifyIdFormatRequest
    // ModifyIdentityIdFormatRequest
    // ModifyImageAttributeRequest
    // ModifyInstanceAttributeRequest
    // ModifyInstanceCapacityReservationAttributesRequest
    // ModifyInstanceCreditSpecificationRequest
    // ModifyInstanceEventStartTimeRequest
    // ModifyInstanceMetadataOptionsRequest
    // ModifyInstancePlacementRequest
    // ModifyLaunchTemplateRequest
    // ModifyManagedPrefixListRequest
    // ModifyNetworkInterfaceAttributeRequest
    // ModifyReservedInstancesRequest
    // ModifySnapshotAttributeRequest
    // ModifySpotFleetRequestRequest
    // ModifySubnetAttributeRequest
    // ModifyTrafficMirrorFilterNetworkServicesRequest
    // ModifyTrafficMirrorFilterRuleRequest
    // ModifyTrafficMirrorSessionRequest
    // ModifyTransitGatewayPrefixListReferenceRequest
    // ModifyTransitGatewayRequest
    // ModifyTransitGatewayVpcAttachmentRequest
    // ModifyVolumeAttributeRequest
    // ModifyVolumeRequest
    // ModifyVpcAttributeRequest
    // ModifyVpcEndpointConnectionNotificationRequest
    // ModifyVpcEndpointRequest
    // ModifyVpcEndpointServiceConfigurationRequest
    // ModifyVpcEndpointServicePermissionsRequest
    // ModifyVpcPeeringConnectionOptionsRequest
    // ModifyVpcTenancyRequest
    // ModifyVpnConnectionOptionsRequest
    // ModifyVpnConnectionRequest
    // ModifyVpnTunnelCertificateRequest
    // ModifyVpnTunnelOptionsRequest
    // MonitorInstancesRequest
    // MoveAddressToVpcRequest
    // ProvisionByoipCidrRequest
    // PurchaseHostReservationRequest
    // PurchaseReservedInstancesOfferingRequest
    // PurchaseScheduledInstancesRequest
    // RebootInstancesRequest
    // RegisterImageRequest
    // RegisterInstanceEventNotificationAttributesRequest
    // RegisterTransitGatewayMulticastGroupMembersRequest
    // RegisterTransitGatewayMulticastGroupSourcesRequest
    // RejectTransitGatewayMulticastDomainAssociationsRequest
    // RejectTransitGatewayPeeringAttachmentRequest
    // RejectTransitGatewayVpcAttachmentRequest
    // RejectVpcEndpointConnectionsRequest
    // RejectVpcPeeringConnectionRequest
    // ReleaseAddressRequest
    // ReleaseHostsRequest
    // ReplaceIamInstanceProfileAssociationRequest
    // ReplaceNetworkAclAssociationRequest
    // ReplaceNetworkAclEntryRequest
    // ReplaceRouteRequest
    // ReplaceRouteTableAssociationRequest
    // ReplaceTransitGatewayRouteRequest
    // ReportInstanceStatusRequest
    // RequestSpotFleetRequest
    // RequestSpotInstancesRequest
    // ResetAddressAttributeRequest
    // ResetEbsDefaultKmsKeyIdRequest
    // ResetFpgaImageAttributeRequest
    // ResetImageAttributeRequest
    // ResetInstanceAttributeRequest
    // ResetNetworkInterfaceAttributeRequest
    // ResetSnapshotAttributeRequest
    // RestoreAddressToClassicRequest
    // RestoreManagedPrefixListVersionRequest
    // RevokeClientVpnIngressRequest
    // RevokeSecurityGroupEgressRequest
    // RevokeSecurityGroupIngressRequest
    // RunInstancesRequest
    // RunScheduledInstancesRequest
    // SearchLocalGatewayRoutesRequest
    // SearchTransitGatewayMulticastGroupsRequest
    // SearchTransitGatewayRoutesRequest
    // SendDiagnosticInterruptRequest
    // StartInstancesRequest
    // StartNetworkInsightsAnalysisRequest
    // StartVpcEndpointServicePrivateDnsVerificationRequest
    // StopInstancesRequest
    // TerminateClientVpnConnectionsRequest
    // TerminateInstancesRequest
    // UnassignIpv6AddressesRequest
    // UnassignPrivateIpAddressesRequest
    // UnmonitorInstancesRequest
    // UpdateSecurityGroupRuleDescriptionsEgressRequest
    // UpdateSecurityGroupRuleDescriptionsIngressRequest
    // WithdrawByoipCidrRequest

  }

  // smartConstructors that take paramteers derived from mandatory & optional fields of requests
}
