package goober.hi

import goober.free.iot.IotIO
import software.amazon.awssdk.services.iot.model._


object iot {
  import goober.free.{iot ⇒ free}

  object model {
    import goober.hi.util.BuilderSyntax._

    // Methods for constructing model classes, requests, etc.
    // AcceptCertificateTransferRequest
    // AddThingToBillingGroupRequest
    // AddThingToThingGroupRequest
    // AssociateTargetsWithJobRequest
    // AttachPolicyRequest
    // AttachSecurityProfileRequest
    // AttachThingPrincipalRequest
    // CancelAuditMitigationActionsTaskRequest
    // CancelAuditTaskRequest
    // CancelCertificateTransferRequest
    // CancelDetectMitigationActionsTaskRequest
    // CancelJobRequest
    // CancelJobExecutionRequest
    // ClearDefaultAuthorizerRequest
    // ConfirmTopicRuleDestinationRequest
    // CreateAuditSuppressionRequest
    // CreateAuthorizerRequest
    // CreateBillingGroupRequest
    // CreateCertificateFromCsrRequest
    // CreateCustomMetricRequest
    // CreateDimensionRequest
    // CreateDomainConfigurationRequest
    // CreateDynamicThingGroupRequest
    // CreateJobRequest
    // CreateJobTemplateRequest
    // CreateKeysAndCertificateRequest
    // CreateMitigationActionRequest
    // CreateOtaUpdateRequest
    // CreatePolicyRequest
    // CreatePolicyVersionRequest
    // CreateProvisioningClaimRequest
    // CreateProvisioningTemplateRequest
    // CreateProvisioningTemplateVersionRequest
    // CreateRoleAliasRequest
    // CreateScheduledAuditRequest
    // CreateSecurityProfileRequest
    // CreateStreamRequest
    // CreateThingRequest
    // CreateThingGroupRequest
    // CreateThingTypeRequest
    // CreateTopicRuleRequest
    // CreateTopicRuleDestinationRequest
    // DeleteAccountAuditConfigurationRequest
    // DeleteAuditSuppressionRequest
    // DeleteAuthorizerRequest
    // DeleteBillingGroupRequest
    // DeleteCaCertificateRequest
    // DeleteCertificateRequest
    // DeleteCustomMetricRequest
    // DeleteDimensionRequest
    // DeleteDomainConfigurationRequest
    // DeleteDynamicThingGroupRequest
    // DeleteJobRequest
    // DeleteJobExecutionRequest
    // DeleteJobTemplateRequest
    // DeleteMitigationActionRequest
    // DeleteOtaUpdateRequest
    // DeletePolicyRequest
    // DeletePolicyVersionRequest
    // DeleteProvisioningTemplateRequest
    // DeleteProvisioningTemplateVersionRequest
    // DeleteRegistrationCodeRequest
    // DeleteRoleAliasRequest
    // DeleteScheduledAuditRequest
    // DeleteSecurityProfileRequest
    // DeleteStreamRequest
    // DeleteThingRequest
    // DeleteThingGroupRequest
    // DeleteThingTypeRequest
    // DeleteTopicRuleRequest
    // DeleteTopicRuleDestinationRequest
    // DeleteV2LoggingLevelRequest
    // DeprecateThingTypeRequest
    // DescribeAccountAuditConfigurationRequest
    // DescribeAuditFindingRequest
    // DescribeAuditMitigationActionsTaskRequest
    // DescribeAuditSuppressionRequest
    // DescribeAuditTaskRequest
    // DescribeAuthorizerRequest
    // DescribeBillingGroupRequest
    // DescribeCaCertificateRequest
    // DescribeCertificateRequest
    // DescribeCustomMetricRequest
    // DescribeDefaultAuthorizerRequest
    // DescribeDetectMitigationActionsTaskRequest
    // DescribeDimensionRequest
    // DescribeDomainConfigurationRequest
    // DescribeEndpointRequest
    // DescribeEventConfigurationsRequest
    // DescribeIndexRequest
    // DescribeJobRequest
    // DescribeJobExecutionRequest
    // DescribeJobTemplateRequest
    // DescribeMitigationActionRequest
    // DescribeProvisioningTemplateRequest
    // DescribeProvisioningTemplateVersionRequest
    // DescribeRoleAliasRequest
    // DescribeScheduledAuditRequest
    // DescribeSecurityProfileRequest
    // DescribeStreamRequest
    // DescribeThingRequest
    // DescribeThingGroupRequest
    // DescribeThingRegistrationTaskRequest
    // DescribeThingTypeRequest
    // DetachPolicyRequest
    // DetachSecurityProfileRequest
    // DetachThingPrincipalRequest
    // DisableTopicRuleRequest
    // EnableTopicRuleRequest
    // GetBehaviorModelTrainingSummariesRequest
    // GetCardinalityRequest
    // GetEffectivePoliciesRequest
    // GetIndexingConfigurationRequest
    // GetJobDocumentRequest
    // GetLoggingOptionsRequest
    // GetOtaUpdateRequest
    // GetPercentilesRequest
    // GetPolicyRequest
    // GetPolicyVersionRequest
    // GetRegistrationCodeRequest
    // GetStatisticsRequest
    // GetTopicRuleRequest
    // GetTopicRuleDestinationRequest
    // GetV2LoggingOptionsRequest
    // ListActiveViolationsRequest
    // ListAttachedPoliciesRequest
    // ListAuditFindingsRequest
    // ListAuditMitigationActionsExecutionsRequest
    // ListAuditMitigationActionsTasksRequest
    // ListAuditSuppressionsRequest
    // ListAuditTasksRequest
    // ListAuthorizersRequest
    // ListBillingGroupsRequest
    // ListCaCertificatesRequest
    // ListCertificatesRequest
    // ListCertificatesByCaRequest
    // ListCustomMetricsRequest
    // ListDetectMitigationActionsExecutionsRequest
    // ListDetectMitigationActionsTasksRequest
    // ListDimensionsRequest
    // ListDomainConfigurationsRequest
    // ListIndicesRequest
    // ListJobExecutionsForJobRequest
    // ListJobExecutionsForThingRequest
    // ListJobTemplatesRequest
    // ListJobsRequest
    // ListMitigationActionsRequest
    // ListOtaUpdatesRequest
    // ListOutgoingCertificatesRequest
    // ListPoliciesRequest
    // ListPolicyVersionsRequest
    // ListPrincipalThingsRequest
    // ListProvisioningTemplateVersionsRequest
    // ListProvisioningTemplatesRequest
    // ListRoleAliasesRequest
    // ListScheduledAuditsRequest
    // ListSecurityProfilesRequest
    // ListSecurityProfilesForTargetRequest
    // ListStreamsRequest
    // ListTagsForResourceRequest
    // ListTargetsForPolicyRequest
    // ListTargetsForSecurityProfileRequest
    // ListThingGroupsRequest
    // ListThingGroupsForThingRequest
    // ListThingPrincipalsRequest
    // ListThingRegistrationTaskReportsRequest
    // ListThingRegistrationTasksRequest
    // ListThingTypesRequest
    // ListThingsRequest
    // ListThingsInBillingGroupRequest
    // ListThingsInThingGroupRequest
    // ListTopicRuleDestinationsRequest
    // ListTopicRulesRequest
    // ListV2LoggingLevelsRequest
    // ListViolationEventsRequest
    // RegisterCaCertificateRequest
    // RegisterCertificateRequest
    // RegisterCertificateWithoutCaRequest
    // RegisterThingRequest
    // RejectCertificateTransferRequest
    // RemoveThingFromBillingGroupRequest
    // RemoveThingFromThingGroupRequest
    // ReplaceTopicRuleRequest
    // SearchIndexRequest
    // SetDefaultAuthorizerRequest
    // SetDefaultPolicyVersionRequest
    // SetLoggingOptionsRequest
    // SetV2LoggingLevelRequest
    // SetV2LoggingOptionsRequest
    // StartAuditMitigationActionsTaskRequest
    // StartDetectMitigationActionsTaskRequest
    // StartOnDemandAuditTaskRequest
    // StartThingRegistrationTaskRequest
    // StopThingRegistrationTaskRequest
    // TagResourceRequest
    // TestAuthorizationRequest
    // TestInvokeAuthorizerRequest
    // TransferCertificateRequest
    // UntagResourceRequest
    // UpdateAccountAuditConfigurationRequest
    // UpdateAuditSuppressionRequest
    // UpdateAuthorizerRequest
    // UpdateBillingGroupRequest
    // UpdateCaCertificateRequest
    // UpdateCertificateRequest
    // UpdateCustomMetricRequest
    // UpdateDimensionRequest
    // UpdateDomainConfigurationRequest
    // UpdateDynamicThingGroupRequest
    // UpdateEventConfigurationsRequest
    // UpdateIndexingConfigurationRequest
    // UpdateJobRequest
    // UpdateMitigationActionRequest
    // UpdateProvisioningTemplateRequest
    // UpdateRoleAliasRequest
    // UpdateScheduledAuditRequest
    // UpdateSecurityProfileRequest
    // UpdateStreamRequest
    // UpdateThingRequest
    // UpdateThingGroupRequest
    // UpdateThingGroupsForThingRequest
    // UpdateTopicRuleDestinationRequest
    // ValidateSecurityProfileBehaviorsRequest

  }

  // smartConstructors that take paramteers derived from mandatory & optional fields of requests
}
