package goober.hi

import goober.free.lightsail.LightsailIO
import software.amazon.awssdk.services.lightsail.model._


object lightsail {
  import goober.free.{lightsail ⇒ free}

  object model {
    import goober.hi.util.BuilderSyntax._

    // Methods for constructing model classes, requests, etc.
    // AllocateStaticIpRequest
    // AttachCertificateToDistributionRequest
    // AttachDiskRequest
    // AttachInstancesToLoadBalancerRequest
    // AttachLoadBalancerTlsCertificateRequest
    // AttachStaticIpRequest
    // CloseInstancePublicPortsRequest
    // CopySnapshotRequest
    // CreateCertificateRequest
    // CreateCloudFormationStackRequest
    // CreateContactMethodRequest
    // CreateContainerServiceRequest
    // CreateContainerServiceDeploymentRequest
    // CreateContainerServiceRegistryLoginRequest
    // CreateDiskRequest
    // CreateDiskFromSnapshotRequest
    // CreateDiskSnapshotRequest
    // CreateDistributionRequest
    // CreateDomainRequest
    // CreateDomainEntryRequest
    // CreateInstanceSnapshotRequest
    // CreateInstancesRequest
    // CreateInstancesFromSnapshotRequest
    // CreateKeyPairRequest
    // CreateLoadBalancerRequest
    // CreateLoadBalancerTlsCertificateRequest
    // CreateRelationalDatabaseRequest
    // CreateRelationalDatabaseFromSnapshotRequest
    // CreateRelationalDatabaseSnapshotRequest
    // DeleteAlarmRequest
    // DeleteAutoSnapshotRequest
    // DeleteCertificateRequest
    // DeleteContactMethodRequest
    // DeleteContainerImageRequest
    // DeleteContainerServiceRequest
    // DeleteDiskRequest
    // DeleteDiskSnapshotRequest
    // DeleteDistributionRequest
    // DeleteDomainRequest
    // DeleteDomainEntryRequest
    // DeleteInstanceRequest
    // DeleteInstanceSnapshotRequest
    // DeleteKeyPairRequest
    // DeleteKnownHostKeysRequest
    // DeleteLoadBalancerRequest
    // DeleteLoadBalancerTlsCertificateRequest
    // DeleteRelationalDatabaseRequest
    // DeleteRelationalDatabaseSnapshotRequest
    // DetachCertificateFromDistributionRequest
    // DetachDiskRequest
    // DetachInstancesFromLoadBalancerRequest
    // DetachStaticIpRequest
    // DisableAddOnRequest
    // DownloadDefaultKeyPairRequest
    // EnableAddOnRequest
    // ExportSnapshotRequest
    // GetActiveNamesRequest
    // GetAlarmsRequest
    // GetAutoSnapshotsRequest
    // GetBlueprintsRequest
    // GetBundlesRequest
    // GetCertificatesRequest
    // GetCloudFormationStackRecordsRequest
    // GetContactMethodsRequest
    // GetContainerApiMetadataRequest
    // GetContainerImagesRequest
    // GetContainerLogRequest
    // GetContainerServiceDeploymentsRequest
    // GetContainerServiceMetricDataRequest
    // GetContainerServicePowersRequest
    // GetContainerServicesRequest
    // GetDiskRequest
    // GetDiskSnapshotRequest
    // GetDiskSnapshotsRequest
    // GetDisksRequest
    // GetDistributionBundlesRequest
    // GetDistributionLatestCacheResetRequest
    // GetDistributionMetricDataRequest
    // GetDistributionsRequest
    // GetDomainRequest
    // GetDomainsRequest
    // GetExportSnapshotRecordsRequest
    // GetInstanceRequest
    // GetInstanceAccessDetailsRequest
    // GetInstanceMetricDataRequest
    // GetInstancePortStatesRequest
    // GetInstanceSnapshotRequest
    // GetInstanceSnapshotsRequest
    // GetInstanceStateRequest
    // GetInstancesRequest
    // GetKeyPairRequest
    // GetKeyPairsRequest
    // GetLoadBalancerRequest
    // GetLoadBalancerMetricDataRequest
    // GetLoadBalancerTlsCertificatesRequest
    // GetLoadBalancersRequest
    // GetOperationRequest
    // GetOperationsRequest
    // GetOperationsForResourceRequest
    // GetRegionsRequest
    // GetRelationalDatabaseRequest
    // GetRelationalDatabaseBlueprintsRequest
    // GetRelationalDatabaseBundlesRequest
    // GetRelationalDatabaseEventsRequest
    // GetRelationalDatabaseLogEventsRequest
    // GetRelationalDatabaseLogStreamsRequest
    // GetRelationalDatabaseMasterUserPasswordRequest
    // GetRelationalDatabaseMetricDataRequest
    // GetRelationalDatabaseParametersRequest
    // GetRelationalDatabaseSnapshotRequest
    // GetRelationalDatabaseSnapshotsRequest
    // GetRelationalDatabasesRequest
    // GetStaticIpRequest
    // GetStaticIpsRequest
    // ImportKeyPairRequest
    // IsVpcPeeredRequest
    // OpenInstancePublicPortsRequest
    // PeerVpcRequest
    // PutAlarmRequest
    // PutInstancePublicPortsRequest
    // RebootInstanceRequest
    // RebootRelationalDatabaseRequest
    // RegisterContainerImageRequest
    // ReleaseStaticIpRequest
    // ResetDistributionCacheRequest
    // SendContactMethodVerificationRequest
    // SetIpAddressTypeRequest
    // StartInstanceRequest
    // StartRelationalDatabaseRequest
    // StopInstanceRequest
    // StopRelationalDatabaseRequest
    // TagResourceRequest
    // TestAlarmRequest
    // UnpeerVpcRequest
    // UntagResourceRequest
    // UpdateContainerServiceRequest
    // UpdateDistributionRequest
    // UpdateDistributionBundleRequest
    // UpdateDomainEntryRequest
    // UpdateLoadBalancerAttributeRequest
    // UpdateRelationalDatabaseRequest
    // UpdateRelationalDatabaseParametersRequest

  }

  // smartConstructors that take paramteers derived from mandatory & optional fields of requests
}
